# Generated by Django 3.2.3 on 2021-05-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captured_Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('a_level', models.IntegerField(default=1)),
                ('nick', models.CharField(max_length=200)),
                ('pockeball', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('effective_agains', models.ManyToManyField(blank=True, null=True, related_name='_pokemon_world_element_effective_agains_+', to='pokemon_world.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='pokemon_world.element')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settlemen',
            fields=[
                ('id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='pokemon_world.region')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='pokemon_world.citizen')),
                ('gym_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_member', to='pokemon_world.gym')),
                ('medals', models.ManyToManyField(blank=True, to='pokemon_world.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('settlemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlemen', to='pokemon_world.settlemen')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('legendary', models.BooleanField(default=False)),
                ('movements', models.ManyToManyField(blank=True, to='pokemon_world.Movement')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='species',
            field=models.ManyToManyField(blank=True, to='pokemon_world.Specie'),
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
                ('sex', models.CharField(max_length=1)),
                ('chainy', models.BooleanField(default=False)),
                ('nature', models.CharField(max_length=200)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_by', to='pokemon_world.trainer')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
                ('movements', models.ManyToManyField(blank=True, to='pokemon_world.Movement')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specie', to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Own',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='pokemon_world.trainer'),
        ),
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='pokemon_world.city'),
        ),
        migrations.AddField(
            model_name='gym',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_element', to='pokemon_world.element'),
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('participants', models.ManyToManyField(to='pokemon_world.Captured_Pokemon')),
                ('settlemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_settlemen', to='pokemon_world.settlemen')),
                ('trainer_loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_loss', to='pokemon_world.trainer')),
                ('trainer_win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_win', to='pokemon_world.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='born_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='born_region', to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='live_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_region', to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='captured_pokemon',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured', to='pokemon_world.pokemon'),
        ),
        migrations.AddField(
            model_name='captured_pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captor', to='pokemon_world.trainer'),
        ),
    ]
