# Generated by Django 3.2.3 on 2021-05-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captured_Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('a_level', models.IntegerField(default=1)),
                ('nick', models.CharField(max_length=200)),
                ('pockeball', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.date')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.city')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settlemen',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('legendary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.citizen')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region')),
                ('settlemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.settlemen')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
                ('sex', models.CharField(max_length=1)),
                ('nature', models.CharField(max_length=200)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.duel')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.captured_pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Own',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.citizen')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.gym')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='KnowsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Knows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Inhabited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Got_Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.gym')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.citizen')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Effective_Against',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element2', to='pokemon_world.element')),
                ('elemnt_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
            ],
        ),
        migrations.AddField(
            model_name='duel',
            name='settlemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.settlemen'),
        ),
        migrations.AddField(
            model_name='duel',
            name='trainer_loss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_loss', to='pokemon_world.trainer'),
        ),
        migrations.AddField(
            model_name='duel',
            name='trainer_win',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='captured_pokemon',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.pokemon'),
        ),
        migrations.AddField(
            model_name='captured_pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer'),
        ),
        migrations.CreateModel(
            name='BelongsE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.pokemon')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
    ]
