# Generated by Django 3.2.3 on 2021-05-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captured_Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('a_level', models.IntegerField(default=1)),
                ('nick', models.CharField(max_length=200)),
                ('pockeball', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cz_id', models.CharField(max_length=200)),
                ('c_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('Age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('s_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duel_id', models.CharField(max_length=200)),
                ('date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.date')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.CharField(max_length=200)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.city')),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200)),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('r_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settlemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=200)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('legendary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=200)),
                ('cz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.citizen')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=200)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.settlemen')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_id', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
                ('p_sex', models.CharField(max_length=1)),
                ('nature', models.CharField(max_length=200)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.duel')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.captured_pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Own',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.citizen')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.gym')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='KnowsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Knows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.movement')),
                ('pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Inhabited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Got_Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.citizen')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.gym')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Effective_Against',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
            ],
        ),
        migrations.AddField(
            model_name='duel',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.settlemen'),
        ),
        migrations.AddField(
            model_name='duel',
            name='tw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer'),
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='b_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.region'),
        ),
        migrations.AddField(
            model_name='captured_pokemon',
            name='pk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.pokemon'),
        ),
        migrations.AddField(
            model_name='captured_pokemon',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.trainer'),
        ),
        migrations.CreateModel(
            name='BelongsE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.element')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.pokemon')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_world.specie')),
            ],
        ),
    ]
