# Generated by Django 3.2.3 on 2021-05-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='participants',
            field=models.ManyToManyField(to='pokemon_world.Captured_Pokemon'),
        ),
    ]
