# Generated by Django 3.2.3 on 2021-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='effective_agains',
            field=models.ManyToManyField(null=True, related_name='_pokemon_world_element_effective_agains_+', to='pokemon_world.Element'),
        ),
    ]
