# Generated by Django 3.2.3 on 2021-05-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='gym_member',
            new_name='gym',
        ),
        migrations.AddField(
            model_name='trainer',
            name='personalkey',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_gym', to='pokemon_world.trainer'),
        ),
    ]
