# Generated by Django 3.2.3 on 2021-05-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlemen',
            name='id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
