# Generated by Django 3.2.3 on 2021-05-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0002_alter_element_effective_agains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='gym',
        ),
        migrations.AlterField(
            model_name='element',
            name='effective_agains',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pokemon_world_element_effective_agains_+', to='pokemon_world.Element'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_by', to='pokemon_world.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='movements',
            field=models.ManyToManyField(blank=True, to='pokemon_world.Movement'),
        ),
        migrations.AlterField(
            model_name='region',
            name='species',
            field=models.ManyToManyField(blank=True, to='pokemon_world.Specie'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gym_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_member', to='pokemon_world.gym'),
        ),
    ]
