# Generated by Django 3.2.3 on 2021-05-29 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0002_alter_duel_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='pokemon_world.citizen'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='medals',
            field=models.ManyToManyField(blank=True, to='pokemon_world.Gym'),
        ),
    ]
