# Generated by Django 3.2.3 on 2021-05-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0003_auto_20210528_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='pokemon_world.element'),
        ),
    ]
