# Generated by Django 3.2.3 on 2021-05-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_world', '0003_auto_20210531_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='boss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_gym', to='pokemon_world.trainer'),
        ),
    ]
