from django.contrib import admin
from . import models


admin.site.register(models.Element)
admin.site.register(models.Movement)
admin.site.register(models.Date)
admin.site.register(models.Region)
admin.site.register(models.Citizen)
admin.site.register(models.City)
admin.site.register(models.Gym)
admin.site.register(models.Trainer)
admin.site.register(models.Pokemon)
admin.site.register(models.Knows)
admin.site.register(models.Leads)
admin.site.register(models.Got_Medals)
admin.site.register(models.Specie)
admin.site.register(models.Belongs)
admin.site.register(models.Inhabited)
admin.site.register(models.Own)
admin.site.register(models.Teach)
admin.site.register(models.Settlemen)
admin.site.register(models.Town)
admin.site.register(models.Effective_Against)
admin.site.register(models.BelongsE)
admin.site.register(models.KnowsM)
admin.site.register(models.Duel)
admin.site.register(models.Captured_Pokemon)
admin.site.register(models.Plays)

